!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 768
  - - clip_range
    - 0.1
  - - ent_coef
    - 1.312836252706057e-05
  - - frame_stack
    - 4
  - - gae_lambda
    - 0.99
  - - gamma
    - 0.995
  - - learning_rate
    - 1.0e-05
  - - max_grad_norm
    - 0.5
  - - n_envs
    - 16
  - - n_epochs
    - 20
  - - n_steps
    - 768
  - - n_timesteps
    - 1000000000.0
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(activation_fn=nn.Tanh, net_arch=[dict(pi=[256, 512, 512, 256], vf=[256,
      512, 512, 256])] )
  - - vf_coef
    - 0.5
